# Generated by Django 2.1.2 on 2018-10-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(db_column='Car_ID', primary_key=True, serialize=False)),
                ('car_makename', models.CharField(blank=True, db_column='Car_MakeName', max_length=45, null=True)),
                ('car_model', models.CharField(blank=True, db_column='Car_Model', max_length=45, null=True)),
                ('car_series', models.CharField(blank=True, db_column='Car_Series', max_length=45, null=True)),
                ('car_seriesyear', models.IntegerField(blank=True, db_column='Car_SeriesYear', null=True)),
                ('car_pricenew', models.IntegerField(blank=True, db_column='Car_PriceNew', null=True)),
                ('car_enginesize', models.CharField(blank=True, db_column='Car_EngineSize', max_length=45, null=True)),
                ('car_fuelsystem', models.CharField(blank=True, db_column='Car_FuelSystem', max_length=45, null=True)),
                ('car_tankcapacity', models.CharField(blank=True, db_column='Car_TankCapacity', max_length=45, null=True)),
                ('car_power', models.CharField(blank=True, db_column='Car_Power', max_length=45, null=True)),
                ('car_seatingcapacity', models.IntegerField(blank=True, db_column='Car_SeatingCapacity', null=True)),
                ('car_standardtransmission', models.CharField(blank=True, db_column='Car_StandardTransmission', max_length=45, null=True)),
                ('car_bodytype', models.CharField(blank=True, db_column='Car_BodyType', max_length=45, null=True)),
                ('car_drive', models.CharField(blank=True, db_column='Car_Drive', max_length=45, null=True)),
                ('car_wheelbase', models.CharField(blank=True, db_column='Car_Wheelbase', max_length=45, null=True)),
                ('car_rentalprice', models.IntegerField(blank=True, db_column='Car_RentalPrice', null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarLocations',
            fields=[
                ('location_id', models.IntegerField(db_column='Location_ID', primary_key=True, serialize=False)),
                ('car_id', models.IntegerField(db_column='Car_ID')),
                ('location_last', models.CharField(db_column='Location_Last', max_length=45)),
                ('location_out', models.IntegerField(db_column='Location_Out')),
            ],
            options={
                'db_table': 'car_locations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carservice',
            fields=[
                ('service_id', models.IntegerField(db_column='Service_ID', primary_key=True, serialize=False)),
                ('car_id', models.IntegerField(db_column='Car_ID')),
                ('service_date', models.DateField(db_column='Service_Date')),
                ('service_location', models.CharField(blank=True, db_column='Service_Location', max_length=45, null=True)),
                ('service_price', models.IntegerField(blank=True, db_column='Service_Price', null=True)),
                ('service_issue', models.CharField(blank=True, db_column='Service_Issue', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carservice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, db_column='Customer_Name', max_length=45, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='Customer_Phone', max_length=45, null=True)),
                ('customer_addresss', models.CharField(blank=True, db_column='Customer_Addresss', max_length=45, null=True)),
                ('customer_brithday', models.DateField(blank=True, db_column='Customer_Brithday', null=True)),
                ('customer_occupation', models.CharField(blank=True, db_column='Customer_Occupation', max_length=45, null=True)),
                ('customer_gender', models.CharField(blank=True, db_column='Customer_Gender', max_length=45, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lostproperty',
            fields=[
                ('lostp_id', models.IntegerField(db_column='LostP_ID', primary_key=True, serialize=False)),
                ('lostp_order_id', models.IntegerField(blank=True, db_column='LostP_Order_ID', null=True)),
                ('lostp_description', models.CharField(blank=True, db_column='LostP_Description', max_length=45, null=True)),
            ],
            options={
                'db_table': 'lostproperty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(db_column='Order_ID', primary_key=True, serialize=False)),
                ('order_createdate', models.DateField(blank=True, db_column='Order_CreateDate', null=True)),
                ('order_pickupdate', models.DateField(blank=True, db_column='Order_PickupDate', null=True)),
                ('order_pickupstore', models.IntegerField(blank=True, db_column='Order_PickupStore', null=True)),
                ('order_returndate', models.DateField(blank=True, db_column='Order_ReturnDate', null=True)),
                ('customer_id', models.IntegerField(blank=True, db_column='Customer_ID', null=True)),
                ('car_id', models.IntegerField(blank=True, db_column='Car_ID', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(db_column='Staff_ID', primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=45, null=True)),
                ('staff_phone', models.CharField(blank=True, db_column='Staff_Phone', max_length=45, null=True)),
                ('staff_address', models.CharField(blank=True, db_column='Staff_Address', max_length=45, null=True)),
                ('staff_birthday', models.DateField(blank=True, db_column='Staff_Birthday', null=True)),
                ('staff_position', models.CharField(blank=True, db_column='Staff_Position', max_length=45, null=True)),
                ('staff_gender', models.CharField(blank=True, db_column='Staff_Gender', max_length=45, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(db_column='Store_ID', primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, db_column='Store_Name', max_length=45, null=True)),
                ('store_address', models.CharField(blank=True, db_column='Store_Address', max_length=45, null=True)),
                ('store_phone', models.CharField(blank=True, db_column='Store_Phone', max_length=45, null=True)),
                ('store_city', models.CharField(blank=True, db_column='Store_City', max_length=45, null=True)),
                ('store_state_name', models.CharField(blank=True, db_column='Store_State_Name', max_length=45, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': True,
            },
        ),
    ]
