# Generated by Django 2.1 on 2018-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carservice',
            fields=[
                ('service_id', models.IntegerField(db_column='Service_ID', primary_key=True, serialize=False)),
                ('car_id', models.IntegerField(db_column='Car_ID')),
                ('service_date', models.DateField(db_column='Service_Date')),
                ('service_location', models.CharField(blank=True, db_column='Service_Location', max_length=45, null=True)),
                ('service_price', models.IntegerField(blank=True, db_column='Service_Price', null=True)),
                ('service_issue', models.CharField(blank=True, db_column='Service_Issue', max_length=45, null=True)),
            ],
            options={
                'db_table': 'carservice',
                'managed': True,
            },
        ),
    ]
